name: autoshool
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  shared_preferences: ^2.0.7
  http: ^1.2.1
  url_launcher: ^6.2.5
  easy_localization: ^3.0.5
  image: ^4.2.0
  search_page: ^2.3.0
  hexcolor: ^3.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\groups.png
    - assets\images\users.png
    - assets\images\cars.png
    - assets/translations/
    - assets/icons/
    
